//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareConfigurationEmulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkInterfaceController
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NetworkInterfaceController()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> GenerationId { get; set; }
        public string Model { get; set; }
        public string TypeOfAdapter { get; set; }
        public Nullable<int> TransmissionSpeed { get; set; }
        public string Path { get; set; }
    
        public virtual Generation Generation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
