//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareConfigurationEmulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Switch()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdTypeOfBuffering { get; set; }
        public Nullable<int> BasicTransmissionSpeed { get; set; }
        public Nullable<int> CountOfSwitchPorts { get; set; }
        public string Path { get; set; }
    
        public virtual TypeOfBuffering TypeOfBuffering { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
