//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareConfigurationEmulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> RouterId { get; set; }
        public Nullable<int> SwitchId { get; set; }
        public Nullable<int> NicId { get; set; }
    
        public virtual NetworkInterfaceController NetworkInterfaceController { get; set; }
        public virtual Router Router { get; set; }
        public virtual Switch Switch { get; set; }
    }
}
